function [M,C,G] = dynMats(dtht1,dtht2,tht1,tht2)
%dynMats
%    [M,C,G] = dynMats(DTHT1,DTHT2,THT1,THT2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    06-Dec-2022 14:47:11

t2 = cos(tht1);
t3 = cos(tht2);
t4 = sin(tht1);
t5 = sin(tht2);
t6 = t2.*t3.*2.0;
t7 = t2.*t5.*2.0;
t8 = t3.*t4.*2.0;
t9 = t4.*t5.*2.0;
t10 = -t8;
t11 = t6+t9;
M = reshape([t2.^2.*5.0+t4.^2.*5.0,t11,t11,t3.^2+t5.^2],[2,2]);
if nargout > 1
    t12 = t7+t10;
    C = reshape([0.0,dtht1.*t12,-dtht2.*t12,0.0],[2,2]);
end
if nargout > 2
    G = [t4.*(-9.81e+2./5.0e+1);t5.*(-9.81e+2./1.0e+2)];
end
