function ysd1out = swingFootHeight(q0,q1,tht0,tht1)
%swingFootHeight
%    YSD1OUT = swingFootHeight(Q0,Q1,THT0,THT1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Jan-2023 13:03:51

ysd1out = 1.0./q1.^2.*(cos(q1+tht1)-cos(tht1)+q1.*sin(tht1))+(sin(q0+tht0)-sin(tht0))./q0;
end
