function [h,dhdq,d2hdq2] = lieDerivs(tht0,tht1,tht0des)
%lieDerivs
%    [H,DHDQ,D2HDQ2] = lieDerivs(THT0,THT1,THT0DES)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    27-Oct-2022 10:29:06

h = [tht0-tht0des;tht0+tht1];
if nargout > 1
    dhdq = reshape([0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0],[2,4]);
end
if nargout > 2
    d2hdq2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,4]);
end
