function G = getGroupAction(q0,q1,tht0,tht1)
%getGroupAction
%    G = getGroupAction(Q0,Q1,THT0,THT1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    10-Jan-2023 15:26:02

t2 = cos(tht0);
t3 = cos(tht1);
t4 = sin(tht0);
t5 = sin(tht1);
t6 = q0+tht0;
t7 = q1+tht1;
t8 = q1.^2;
t12 = 1.0./q0.^2;
t14 = 1.0./q1.^3;
t9 = cos(t6);
t10 = sin(t6);
t11 = sin(t7);
t13 = 1.0./t8;
t15 = t5.*(4.9e+1./5.0);
t17 = t2.*t8.*(4.9e+1./5.0);
t19 = t4.*t8.*(9.8e+1./5.0);
t16 = t11.*(4.9e+1./5.0);
t18 = -t17;
t20 = t8.*t9.*(4.9e+1./5.0);
t21 = t8.*t10.*(4.9e+1./5.0);
t22 = -t21;
t23 = t19+t22;
t24 = q0.*t23;
t25 = t18+t20+t24;
G = [-t12.*t13.*(-t19+q0.*t20+t8.*t10.*(9.8e+1./5.0))-1.0./q0.^3.*t13.*t25.*2.0,-t12.*t13.*(t21-t4.*t8.*(4.9e+1./5.0)+q0.*(t20-t2.*t8.*(9.8e+1./5.0))),t13.*(t15-t16)-t14.*(t3.*(-4.9e+1./5.0)+cos(t7).*(4.9e+1./5.0)+q1.*t15).*2.0-t12.*t14.*t25.*2.0+t12.*t13.*(q1.*t2.*(-9.8e+1./5.0)+q1.*t9.*(9.8e+1./5.0)+q0.*(q1.*t4.*(1.96e+2./5.0)-q1.*t10.*(9.8e+1./5.0))),t13.*(t15-t16+q1.*t3.*(4.9e+1./5.0))];
end
