function ysd1 = swingFootHeight(q0,q1,tht0,tht1)
%swingFootHeight
%    YSD1 = swingFootHeight(Q0,Q1,THT0,THT1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Jan-2023 11:59:50

ysd1 = (sin(q0+tht0)-sin(tht0))./q0+(sin(q1+tht1)-sin(tht1))./q1;
end
