function [M,C,G,T,V] = getDynamicsGenerated(I1,I2,a1,a2,dtht1,dtht2,k1,k2,m1,m2,tht1,tht2)
%getDynamicsGenerated
%    [M,C,G,T,V] = getDynamicsGenerated(I1,I2,A1,A2,DTHT1,DTHT2,K1,K2,M1,M2,THT1,THT2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    13-Nov-2022 10:29:58

M = reshape([I1+I2,I2,I2,I2],[2,2]);
if nargout > 1
    C = reshape([0.0,0.0,0.0,0.0],[2,2]);
end
if nargout > 2
    t2 = cos(tht1);
    t3 = sin(tht1);
    t4 = tht1+tht2;
    t5 = sin(t4);
    G = [k1.*tht1+m2.*(a1.*t3+a2.*t5)+a1.*m1.*t3;k2.*tht2+a2.*m2.*t5];
end
if nargout > 3
    T = (I2.*(dtht1+dtht2).^2)./2.0+(I1.*dtht1.^2)./2.0;
end
if nargout > 4
    V = (k1.*tht1.^2)./2.0+(k2.*tht2.^2)./2.0-m2.*(a1.*t2+a2.*cos(t4))-a1.*m1.*t2;
end
